### ISSUE TITLE
get_nodejs_path fails on Windows with MSVS installed nodejs

### ISSUE THREAD

**Issue by nanis** [perlancar/perl-Nodejs-Util#1]
This causes `Data::Sah::Coerce` tests to fail.

```
 C:\...\Data-Sah-Coerce-0.014> perl -MNodejs::Util=get_nodejs_path -E "say get_nodejs_path"
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

Also:

```
C:\...> perl -MFile::Which=which -E "say which 'node'"
C:\Program Files (x86)\nodejs\node.EXE
```

The culprit is on [lines 22-32](https://github.com/perlancar/perl-Nodejs-Util/blob/master/lib/Nodejs/Util.pm#L22) in `lib/Nodejs/Util.pm`.

I don't have time to test at this moment, but:

``` perl
my $cmd = qq{"$path" -e "console.log(1+1)"};
```

should work on Windows.

**Comment by perlancar** [comment]
OK, I've added Win32 shell-quoting to newly released Nodejs::Util (0.004),
Data::Sah::Coerce (0.015), as well as Data::Sah (0.82). At least the
node.js executing part. Please try again.

**Comment by nanis** [comment]
Will do later today.

**Comment by nanis** [comment]
This sent me chasing a bunch of other things, among them a large number of test failures trying to install `IPC::Run`.

**Comment by nanis** [comment]
This sent me chasing a bunch of other things, among them a large number of test failures trying to install `IPC::Run`. The test suite does not complete. It is going to take me a while to figure out what's going on with that.

**Comment by nanis** [comment]
After force installing `IPC::Run`:

> ```
> Building and testing Data-Sah-0.82 ... OK
> Successfully installed Data-Sah-0.82 (upgraded from 0.81)
> ```
> 
> ```
> Building and testing Nodejs-Util-0.004 ... OK
> Successfully installed Nodejs-Util-0.004 (upgraded from 0.003)
> ```
> 
> ```
> Building and testing Data-Sah-Coerce-0.015 ... OK
> Successfully installed Data-Sah-Coerce-0.015 (upgraded from 0.014)
> ```

**Comment by perlancar** [comment]
I was not aware IPC::Run has trouble installing cleanly on Windows. Maybe I can make dependency to IPC::Run.

**Comment by perlancar** [comment]
..optional (previous comment sent too early, on mobile).

**Comment by nanis** [comment]
I think I have figured out the cause of most of the issues with `IPC::Run` tests, but I need to check on older Windows and a couple of other `perl`s first. There is an additional bug relating to warnings about files not closed properly. I think we'd run into a similar issue with `Capture::Tiny`, so I am going to have to look that up as well.

That is, I think `IPC::Run` will be OK soon.
